### ISSUE TITLE
Unexpected Token '('

### ISSUE THREAD

**Issue by Toskan4134** [SimonLeclere/discord-hangman#9]
![image](https://user-images.githubusercontent.com/62228706/119234970-948c9e80-bb30-11eb-9e3c-acbbf5203115.png)

Why is this happening?

**Comment by SimonLeclere** [comment]
Hey, wich Node version are u using ? Do you use repl.it ?

**Comment by SimonLeclere** [comment]
Try using Node v14 or higher or install the node-v12 branch

**Comment by Toskan4134** [comment]
Still not work

**Comment by SimonLeclere** [comment]
> Hey, wich Node version are u using ? Do you use repl.it ?

?

**Comment by Toskan4134** [comment]
im actually using node 14.x

**Comment by SimonLeclere** [comment]
Can u check it ? 

(Use node -v in a terminal)

**Comment by Spongecade** [comment]
If you are using repl.it, you're using node v12 unless you do some weird work around...

Repl.it locks your project at node v12

**Comment by SimonLeclere** [comment]
Closed due to inactivity :(
